config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#index'

  devise_for :users
  resources :users, only: [:show]
  
  resources :pictures do 
    resources :tags, only: [:update]
  end
  resources :tags, only: [:index, :show, :create]

  get 'pages/:page' => 'pages#show'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Picture
    can :read, Tag

    return unless user.present?
    
    can [:update, :destroy, :create], Picture, user: user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/picture.rb
class Picture < ApplicationRecord 
  belongs_to :user
  has_and_belongs_to_many :tags

  has_one_attached :file
  validates :file, 
    attached: true,
    size: { less_than: 5.megabytes , message: 'is too large' },
    content_type: ['image/png', 'image/jpeg']
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_and_belongs_to_many :pictures
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  has_many :pictures
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.html { redirect_to root_path, alert: exception.message }
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
  end

  def index
    @picture = Picture.last
    @demo_pictures = Picture.limit(5).order("RANDOM()").first(5)
    @demo_users = User.limit(5).order("RANDOM()").first(5)
    @demo_tags = Tag.all.sort_by(&:name)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!, :only => [:create, :destroy, :update]
  load_and_authorize_resource

  def show ; end

  def create
    current_user.pictures.create!(picture_params)
    redirect_to user_path(current_user)
  end

  def destroy
    @picture.file.purge
    @picture.destroy
    redirect_to user_path(current_user)
  end

  def update
    tag_id = params[:tag_id]
    
    @picture.tags.destroy(tag_id) if tag_id
   
    unless tag_id
      tag_name = params[:picture][:tag_name]
      tag = Tag.find_by name: tag_name
      unless tag
        @picture.tags.create(name: tag_name)
      else
        @picture.tags = @picture.tags | [tag]
      end
  
      @picture.save
    end

    redirect_to picture_path(@picture)
  end

  protected

  def picture_params
    params.require(:picture).permit(:file)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  load_and_authorize_resource :tag
  load_and_authorize_resource :picture
  
  def index
  end

  def show
    @tag = Tag.find(params[:id])
    @pictures = @tag.pictures
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-error"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Albums</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application",
    type: "module",
    "data-turbo-track": "reload",
    defer: true %>

  </head>

  <body>
    <%= render "shared/flash_render" %>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<section id="home" class="intro-section">
  <div clas="container">
    <div class="row align-items-center text-white">
      <div class="col-md-6 intros">
        <h1 class="intro">
          <span class="display2--intro">
            Albums
          </span>
          <span class="display2--description lh-base">
            the image hosting service
          </span>
        </h1>
        <form>
          <button
            type="submit"
            formaction="<%= current_user ? user_path(current_user) : new_user_session_path %>"
            class="rounded-pill btn-rounded"
          >
            Upload one
            <span>
              <%= icon("fa-solid", "upload") %>
            </span>
          </button>
        </form>
      </div>
      <div class="col-md-6 intros text-end">
        <div class="video-box">
          <div class="portfolio-box text-center">
            <% if @picture %>
              <%= image_tag @picture.file.representation(resize_to_limit: [400, 400]),
              id: "rescently_uploaded" %>
            <% else %>
              <%= image_tag "stub.jpg", id: "stub" %>
            <% end %>
            <%= link_to("#", class: 'glightbox position-absolute top-50 start-50 translate-middle') do %>
              <span><%= icon("fa-solid", "play-circle") %></span>
              <span class="border-animation border-animation--border-1"></span>
              <span class="border-animation border-animation--border-2"></span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
    <path
      fill="#ffffff"
      fill-opacity="1"
      d="M0,192L80,165.3C160,139,320,85,480,90.7C640,96,800,160,960,181.3C1120,203,1280,181,1360,170.7L1440,160L1440,320L1360,320C1280,320,1120,320,960,320C800,320,640,320,480,320C320,320,160,320,80,320L0,320Z"
    ></path>
  </svg>
</section>

<section id="companies" class="companies">
  <div class="container">
    <div class="row text-center">
      <h4 class="fw-bold lead mb-3">Kind of trusted by</h4>
      <div class="heading-line">
      </div>
      <p class="fw-light">
        Different people</p>
    </div>
  </div>
</section>

<section id="services" class="our-services">
  <div class="container">
    <div class="row">
      <div class="row text-center">
        <h1 class="display-3 fw-bold">Our Services</h1>
        <div class="heading-line mb-1">
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row pt-2 pb-2 mt-0 mb-3">
      <div class="col-md-6 border-right">
        <div class="bg-white p-3">
          <h2 class="fw-bold text-capitalize text-center">
            Picture Upload
          </h2>
        </div>
      </div>
      <div class="col-md-6">
        <div class="bg-white p-4 text-start">
          <p class="fw-light">
            Why not upload yours?</p>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 services mt-4 text-start">
        <div class="services__content">
          <%= icon("fa-solid", "circle-user") %>
          <h3 class="display-3--title mt-1">Users uploads</h3>
          <p class="lh-lg">
            You can browse pictures, uploaded by the particular user
          </p>
        </div>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 services mt-4 text-end">
        <div class="services__content">
          <% @demo_users.each do |user| %>
            <%= link_to user.username, user_path(user) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 services mt-4 text-start">
        <div class="services__content">
          <%= icon("fa-solid", "hashtag") %>
          <h3 class="display-3--title mt-1">Tags</h3>
          <p class="lh-lg">
            You can browse pictures by tags and tag your own
          </p>
        </div>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 services mt-4 text-end">
        <div class="services__content">
          <% @demo_tags.each do |tag| %>
            <%= link_to tag.name, tag_path(tag) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 services mt-4 text-start">
        <div class="services__content">
          <%= icon("fa-solid", "star") %>
          <h3 class="display-3--title mt-1">Popular</h3>
          <p class="lh-lg">
            Soon, you could browse pictures by popularity
          </p>
        </div>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 services mt-4 text-end">

        <div class="services__content">
          <section id="listed-pictures" class="portfolio listed_pictures">
            <div class="container">
              <div class="row pictures_list">
                <%= render(
                  partial: "shared/listed_picture",
                  collection: @demo_pictures,
                  as: :picture,
                  locals: {
                    limit: 100
                  }
                ) || "No pictures yet" %>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pictures/show.erb
<div id="picture">
  <%= image_tag @picture.file, id: 'main_pic' %>
</div>

<div id="tags">
<% if @picture.tags.empty? %>
  <p>No tags yet</p>
<% else %>
  <% @picture.tags.each do |tag| %>
    <p id="tag">
      <%= tag.name %>
    </p>
  <% end %>
<% end %>
<%= button_to 'Delete!', @picture, method: 'delete' %>
</div>

app/views/pictures/show.html.erb
<div class="container">
  <p>Upploaded by: <%= link_to @picture.user.username, user_path(@picture.user) %>
  <div id="picture">
    <%= image_tag @picture.file, id: "main_pic", class: "img-fluid" %>
    <div id="tags">
      <%= render(
        partial: "shared/listed_tag",
        locals: {
          picture: @picture
        },
        collection: @picture.tags,
        as: :tag
      ) || "No tags yet" %>
      <% if can? :update, @picture %>
        <%= render(partial: "shared/add_new_tag", locals: { picture: @picture }) %>
      <% end %>

    </div>

    <div class="container clearfix">
      <% if can? :destroy, @picture %>
        <%= button_to "Delete!",
        @picture,
        method: "delete",
        class: "btn btn-outline-danger float-end" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_add_new_tag.html.erb
<div id="new_tag" class="input-group">
  <%= form_with model: picture, method: :patch,  data: { turbo: false } do |f| %>
    <%= f.text_field :tag_name, placeholder: "new tag", size: "10" %>
    <%= button_tag(type: 'submit', class: 'btn btn-sm btn-outline-tertiary', id: 'create_tag') do %>
      <span><i class="fas fa-plus"></i></span>
    <% end %>
  <% end %>
</div>

app/views/shared/_flash_render.html.erb
<% flash.each do |key, value| %>
  <div class="<%= bootstrap_flash_class(key) %>">
    <%= value %>
  </div>
<% end %>

app/views/shared/_listed_picture.html.erb
      <div class="col-lg-4 col-md-6">
        <div class="portfolio-box shadow text-center">
            <%= link_to picture_path picture do %>
              <%= image_tag picture.file.representation(resize_to_limit: [limit, limit]), id: 'main_pic', class: 'img-fluid' %>
            <% end %>
        </div>
      </div>

        
        

app/views/shared/_listed_tag.html.erb
<span class="badge bg-tertiary d-flex align-items-center float-start" id="tag">
  <%= link_to tag.name, tag %>
  <% if can? :update, picture %>
    <span>
      <%= button_to '<i class="fas fa-xmark"></i>'.html_safe,
      picture,
      html_options: {
        method: :patch
      },
      class: "btn btn-sm btn-outline-tertiary",
      params: {
        tag_id: tag.id
      } %>
    </span>
  <% end %>
</span>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark menu shadow sticky-top">
  <div class="container">
    <%= link_to "Albums", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Tags", tags_path, class: "nav-link" %>
        <% unless user_signed_in? %>
          <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class: "nav-link"  %></li>
        <% else %>
          <li class="nav-item">
          <%= link_to current_user.username, user_path(current_user), class: "nav-link"  %>
          </li>
          <li class="nav-item"><%= link_to "Sign out", destroy_user_session_path, class: "nav-link"  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_pic_upload_form.html.erb
<%= form_with model: Picture do |f| %>
  <%= f.label :file, 'New Picture' %>
  <%= f.file_field :file %>
  <%= f.submit 'Upload!', data: { disable_with: "Upploading yet..." }%>
<% end %>

app/views/tags/index.html.erb
<% @tags.each do |tag| %>
    <%= link_to tag.name , tag_path(tag) %>
<% end %>

app/views/tags/show.html.erb
<div class="pictures_list">
  <%= render(partial: 'shared/listed_picture', collection: @pictures, as: :picture, locals: {limit: 500}) || 'No pictures yet' %>
</div>

app/views/users/show.html.erb
<section id="listed-pictures" class="portfolio listed_pictures">
  <div class="container">
    <div class="row pictures_list">
      <%= render(partial: 'shared/listed_picture', collection: @user.pictures, as: :picture, locals: {limit: 500}) || 'No pictures yet' %>
    </div>
  </div>
</section>

<% if user_signed_in?  %>
  <%= render partial: 'shared/pic_upload_form' %>
<% end %>